from .settings import GLPI_USER, GLPI_PASSWORD, GLPI_DATABASE, GLPI_HOST, ZULIP_URL, GLPI_URL, NUMERO_SOPORTE1, NUMERO_SOPORTE2, CORREO_SOPORTE, DOMINIO_CORPORATIVO;
__all__ = [
    "GLPI_USER", 
    "GLPI_PASSWORD", 
    "GLPI_DATABASE", 
    "GLPI_HOST", 
    "ZULIP_URL", 
    "GLPI_URL", 
    "NUMERO_SOPORTE1", 
    "NUMERO_SOPORTE2", 
    "CORREO_SOPORTE", 
    "DOMINIO_CORPORATIVO"
]
