DROP DATABASE IF EXISTS doom_bot;
CREATE DATABASE doom_bot;
USE doom_bot;

CREATE TABLE IF NOT EXISTS origin(
    `id` INT AUTO_INCREMENT NOT NULL,
    `name` VARCHAR(100) NOT NULL,
    CONSTRAINT PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS users(
    `id` INT AUTO_INCREMENT NOT NULL,
    `name` VARCHAR(100) NOT NULL,
    identity VARCHAR(100) NOT NULL UNIQUE,
    id_origin INT NOT NULL,
    CONSTRAINT FOREIGN KEY(id_origin) REFERENCES origin(id),
    CONSTRAINT PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS process(
	`id` INT AUTO_INCREMENT NOT NULL,
    `name` VARCHAR(100) NOT NULL,
    CONSTRAINT PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS steps(
	`id` INT AUTO_INCREMENT NOT NULL,
    `name` VARCHAR(100) NOT NULL,
    id_process INT NOT NULL,
    CONSTRAINT FOREIGN KEY(id_process) REFERENCES process(id),
    CONSTRAINT PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS chats(
	`id` INT AUTO_INCREMENT NOT NULL,
    `serial` VARCHAR(100) NOT NULL UNIQUE,
    status BOOLEAN NOT NULL DEFAULT True,
    date_start DATETIME NOT NULL,
    date_end DATETIME NOT NULL, 
    id_process INT NOT NULL,
    id_steps INT NOT NULL,
    CONSTRAINT FOREIGN KEY(id_process) REFERENCES process(id),
    CONSTRAINT FOREIGN KEY(id_steps) REFERENCES steps(id),
    CONSTRAINT PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS logs_chats(
	`id` INT AUTO_INCREMENT NOT NULL,
    id_chat INT NOT NULL,
    content TEXT NOT NULL,
    CONSTRAINT FOREIGN KEY(id_chat) REFERENCES process(id),
    CONSTRAINT PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS messages(
	`id` INT AUTO_INCREMENT NOT NULL,
    message TEXT NOT NULL,
    id_transmitter INT NOT NULL,
    date DATETIME NOT NULL,
    id_chat INT NOT NULL,
    CONSTRAINT FOREIGN KEY(id_chat) REFERENCES process(id),
    CONSTRAINT PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS participants(
	`id` INT AUTO_INCREMENT NOT NULL,
    id_user INT NOT NULL,
    id_chat INT NOT NULL,
    CONSTRAINT FOREIGN KEY(id_user) REFERENCES users(id),
    CONSTRAINT FOREIGN KEY(id_chat) REFERENCES process(id),
    CONSTRAINT PRIMARY KEY(id)
);